version: "3.9"

services:
  mojo-backend-engine:
    build:
      context: .
      dockerfile: mojobuilder.dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://0.0.0.0:3000/ || exit 1"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - mojo-backend-dbstore:/home/nonroot/mojobuilder/db
    networks:
      - mojo-subnetwork

  mojo-frontend-app:
    build:
      context: .
      dockerfile: mojobuilder.dockerfile
      args:
        - VITE_API_BASE_URL=http://mojo-backend-engine:3000
    depends_on:
      - mojo-backend-engine
    networks:
      - mojo-subnetwork

networks:
  mojo-subnetwork:

volumes:
  mojo-backend-dbstore:
